//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalityPredictionAU
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryScore
    {
        public int AccountId { get; set; }
        public int CategoryId { get; set; }
        public int SourceId { get; set; }
        public double Score { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Category Category { get; set; }
        public virtual Source Source { get; set; }
    }
}
